Update spm

diff --git a/spm b/spm
--- a/spm
+++ b/spm
@@ -3,14 +3,10 @@
 # Copyright © 2024 slashOS Team and Contributors
 
 ### ΤΟ DO ###
+# - Removing packages
 # - Manage flatpak
-# - Manage snap
-# - Manage npm
 # - Updating/Downgrading specific packages
-# - Manage pip (partially implemented, check the entry below)
-# - Updating PIP packages
-# - Searching in all package managers/formats spm wraps around
-# - Config file (when needed, not big priority rn)
+# - Searching
 # - Integration with GNOME Software or creation of a completely new graphical frontend.
 # - Fix bugs (OMG NO WAY!!!1111)
 
@@ -27,18 +23,11 @@ help(){
   echo "                    | (use the -a arguement to install from the AUR instead)"
   echo "        update      | updates all packages"
   echo ""
-  echo "NOTE: Experiemental options are not shown here!"
   exit 0
 }
 
 remove() {
-    sudo pacman -R $1
-    echo "Completed!"    
-}
-
-pipremove() {
-    pip uninstall $1 --break-system-packages
-    exit 0
+    # time to implement proper removing system  
 }
 
 install() {
@@ -61,7 +50,7 @@ aurinstall() {
       echo "Adding $1 to spm AUR package history..."
       sudo echo "$1" >> /etc/spmaurhistory
     else
-      echo "(spm) Error: Installing $1 failed."
+      echo "(spm) Error: Installing $1 from the AUR failed."
       exit 1
     fi
     echo "Removing left over junk files."
@@ -70,8 +59,17 @@ aurinstall() {
 }
 
 pipinstall() {
-    echo "Preparing to install $1"
+    echo "Installing $1 using pip"
     pip install $1 --break-system-packages
+    if [ $? -eq 0 ]; 
+    then
+      echo "$1 was installed successfully."
+      echo "Adding $1 to spm pip package history..."
+      sudo echo "$1" >> /etc/spmpiphistory
+    else
+      echo "(spm) Error: Installing $1 using pip failed."
+      exit 1
+    fi
     exit 0
 }
 
@@ -79,9 +77,13 @@ update() {
    echo "Updating pacman packages..." 
    sudo pacman -Syu
    echo "Updating AUR packages..." 
-   while read -r line; do
-     aurinstall "$line"
+   while read -r apkg; do
+     aurinstall "$apkg"
    done < "/etc/spmaurhistory"
+   echo "Updating pip packages"
+   while read -r ppkg; do
+     aurinstall "$ppkg"
+   done < "/etc/spmpiphistory"
    exit 0
 }
 
@@ -100,9 +102,6 @@ then
 elif [ "$1" == "remove" ] && [ "$#" -eq  2 ]
 then
   remove "$2"
-elif [ "$1" == "remove" ] && [ "$2" == "-p" ] && [ "$#" -eq  3 ]
-then
-  pipremove "$3"
 elif [ "$1" == "update" ] && [ "$#" -eq  1 ]
 then
   update
